from blogfront import BlogFront
from deletepost import DeletePost 
from editcomment import EditComment
from editpost import EditPost
from login import Login
from logout import Logout
from mainpage import MainPage
from newpost import NewPost
from postpage import PostPage
from register import Register
from signup import Signup
